### ISSUE TITLE
LiveKit media server

### ISSUE THREAD

**Issue by jibon57** [bigbluebutton/bbb-webrtc-sfu#105]
[LiveKit](https://github.com/livekit/livekit-server) also looks promising. For recorder can use their [go sdk](https://github.com/livekit/server-sdk-go#interacting-as-a-participant). @prlanzarin You can keep this in your whitelist for future adapter development.

**Comment by prlanzarin** [comment]
Yeah; both Pion and LiveKit (which is Pion-based) are on my experimentation list.
