### ISSUE TITLE
update(audio): make fullaudio module completely bidirectional 

### ISSUE THREAD

**Issue by mariogasparoni** [bigbluebutton/bbb-webrtc-sfu#107]
Today the fullaudio module does a differentiation between microphone and listenonly. Ideally we want to make this bidirectional as default and make ~both listenonly and microphone to use the same module~ **fullaudio module to handle microphone only**

There's also lots of functions specific for listeonly that were kept for compatibility and could be removed when changing this module do be bidirectional : more info can be found in https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/106#issuecomment-948099180 and https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/106#issuecomment-948677762

This is related to: https://github.com/bigbluebutton/bigbluebutton/issues/13539

**Comment by mariogasparoni** [comment]
Adjusted issue name and description according to @prlanzarin 's comment in private chat

**Comment by prlanzarin** [comment]
https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.8.0-alpha.0
