### ISSUE TITLE
update(audio): create a separate redis channel for fullaudio module

### ISSUE THREAD

**Issue by mariogasparoni** [bigbluebutton/bbb-webrtc-sfu#108]
Pointed by @prlanzarin in https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/106#discussion_r733175633.

**Comment by prlanzarin** [comment]
I'll move the listen only module away from the new full audio module and rename its channel instead.

**Comment by mariogasparoni** [comment]
Not sure if i understood well, but avoid refactoring fullaudio module now, i have some important WIP related to mediasoup. If you are talking about audio module, so this is fine. I won't touch that module

**Comment by prlanzarin** [comment]
**`I'll move the listen only module away`**

**Comment by mariogasparoni** [comment]
> **`I'll move the listen only module away`**

Could you be more specific ?

**Comment by prlanzarin** [comment]
5d9780e7fd019660a14e5aeff4dffcd93e4c6407

This. I moved the listen only module away from the /audio folder to a specific folder and created separated/renamed Redis channels, constants and whatnots for it. So the full audio module lands with its constants et al as is, and the listen only module is not crossing wires with the full audio module channels and constants.

**Comment by mariogasparoni** [comment]
Thanks , Paulo. Nice work
