### ISSUE TITLE
Minor wiki documentation suggestions

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bbb-webrtc-sfu#109]
Unfortunately, I can't send a PR for the wiki page, so I'm trying with this issue.

I know the github wiki isn't a "real" documentation yet, but I wanted to let you know two things I stumbled over when trying to enable mediasoup on my 2.4-rc3 server following the section "Using mediasoup in a 2.4 (> RC.2) installation":

1. On my NAT setup, I also had to add the `listenIp: "0.0.0.0"` lines to both the `plainRtp` and `webrtc` section to make it work, as you described in the development section below. So if this is neccessary to make it run behind NAT it would be great if you could add it.
2. As far as I can tell it's not `public.app.kurento.signalCandidates` but `public.kurento.signalCandidates` in the last line of step 3. At least it worked for me and the connection time dropped significantly as I changed it :-)

Thank you for the great work! Really looking forward to using mediasoup in production.

**Comment by prlanzarin** [comment]
> On my NAT setup, I also had to add the listenIp: "0.0.0.0" lines to both the plainRtp and webrtc section to make it work, as you described in the development section below. So if this is neccessary to make it run behind NAT it would be great if you could add it.

Right. Fell into my own trap; arrays are merged by replacement in the overlay file so the default config's 0.0.0.0 is lost on /etc/[...].

> As far as I can tell it's not public.app.kurento.signalCandidates but public.kurento.signalCandidates in the last line of step 3. At least it worked for me and the connection time dropped significantly as I changed it :-)

Fixed.

> Unfortunately, I can't send a PR for the wiki page, so I'm trying with this issue.

Thanks for the heads-up. I have to port these docs over to the official docs, will separate some time to do that this weekend.
