### ISSUE TITLE
Too many mediasoup-worker processes on beefy hardware by default.

### ISSUE THREAD

**Issue by defnull** [bigbluebutton/bbb-webrtc-sfu#112]
I know this can be configured, but there should probably be a sensible upper default limit for `mediasoup-worker`s on hardware with more than, say, 32 cores?

For example: `ceil( min(nproc,32)*0.8 + max(0,nproc-32)/2 )` -> Use 80% of the the first 32 cores, and half of any additional cores beyond 32. This leaves some cores free for other important processes and still scales with large servers.

**Comment by prlanzarin** [comment]
Yup, thanks for registering the issue

**Comment by prlanzarin** [comment]
This has been addressed in https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.7.0-beta.0
This is BBB v2.5 only right now. I don't intend to backport it to BBB v2.4's SFU version, _but_ I do plan to make BBB v2.4 use SFU v2.7 when the latter has a stable release, so eventually it'll trickle down.

I've also added some simple docs for the config flags responsible for controlling the number of workers: https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/development/docs/mediasoup.md#mediasoupworkers-defaultexampleyml-defaultyml-productionyml
