### ISSUE TITLE
Build error: mediasoup fails to build

### ISSUE THREAD

**Issue by georg3k** [bigbluebutton/bbb-webrtc-sfu#118]
Mediasoup version specified in **bbb-webrtc-sfu/package.json** produces an error during build:
```
npm ERR! cc -Isubprojects/libuv-v1.43.0/libuv.a.p -Isubprojects/libuv-v1.43.0 -I../../../subprojects/libuv-v1.43.0 -I../../../subprojects/libuv-v1.43.0/include -I../../../subprojects/libuv-v1.43.0/src -fdiagnostics-color=always -DNDEBUG -std=c89 -O3 -fPIC -pthread -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112 -MD -MQ subprojects/libuv-v1.43.0/libuv.a.p/src_unix_stream.c.o -MF subprojects/libuv-v1.43.0/libuv.a.p/src_unix_stream.c.o.d -o subprojects/libuv-v1.43.0/libuv.a.p/src_unix_stream.c.o -c ../../../subprojects/libuv-v1.43.0/src/unix/stream.c
npm ERR! ../../../subprojects/libuv-v1.43.0/src/unix/stream.c: In function ‘uv__write’:
npm ERR! ../../../subprojects/libuv-v1.43.0/src/unix/stream.c:929:3: error: C++ style comments are not allowed in ISO C90
npm ERR!   929 |   // XXX(jwn): this must call uv__stream_flush_write_queue(stream, n) here, since we won't generate any more events
npm ERR!       |   ^
npm ERR! ../../../subprojects/libuv-v1.43.0/src/unix/stream.c:929:3: note: (this will be reported only once per input file)
```

Setting newer version of mediasoup and mediasoup-client fixes this issue. This problem was encountered here: https://github.com/bigbluebutton/docker/issues/236#issuecomment-1297259842

**Comment by prlanzarin** [comment]
This has been addressed a while ago now, see: https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.8.5.
If you're using an outdated BBB version, update to one that has this app's v2.8.5 version or later.
The docker setup should be updated accordingly as well - which seems it was.

**Comment by prlanzarin** [comment]
Also: the mediasoup-client update is irrelevant and I strongly recommend against deviating from what is specified in this repo unless absolutely necessary or you're willing to deal with any fallout yourself.
