### ISSUE TITLE
Missing 'S' of constant 'WEBSOCKET_MESAGE'

### ISSUE THREAD

**Issue by thitranthanh** [bigbluebutton/bbb-webrtc-sfu#57]
In the message/Constant.js 
WEBSOCKET_MESAGE: "ws_message"

But It used for ConnectionManager.js and WebSocketConnectionManager.js with C.WEBSOCKET_MESSAGE

It's working but let me known if this is not correct.

**Comment by prlanzarin** [comment]
@thitranthanh Good catch, thanks. I've fixed it in #59.

It worked because since the constant didn't exist the event name was casted to `undefined`, but yeah, still a bug.
